// Generated by scripts/generate-checkout-styling-query.mjs from the
// Admin API 2026-10 schema. Don't edit by hand.

/** Scope read_checkout_and_accounts_configurations. One configuration's
 * branding: every field checkoutAndAccountsConfigurationUpdate also
 * accepts. */
export const CHECKOUT_STYLING_QUERY = `#graphql
  query CheckoutStyling($id: ID!) { checkoutAndAccountsConfiguration(id: $id) {
  branding { components { checkbox { cornerRadius } choiceList { group { spacing
  } } control { border cornerRadius labelPosition } divider { borderStyle
  borderWidth } favicon { __typename ... on
  CheckoutAndAccountsConfigurationBrandingImage { image { url } } } footer {
  alignment background colors { base { accent background border decorative icon
  text } control { accent background border decorative icon selected { accent
  background border decorative icon text } text } primaryButton { accent
  background border decorative hover { accent background border decorative icon
  text } icon text } secondaryButton { accent background border decorative hover
  { accent background border decorative icon text } icon text } } content {
  visibility } divided padding } header { alignment background colors { base {
  accent background border decorative icon text } control { accent background
  border decorative icon selected { accent background border decorative icon
  text } text } primaryButton { accent background border decorative hover {
  accent background border decorative icon text } icon text } secondaryButton {
  accent background border decorative hover { accent background border
  decorative icon text } icon text } } divided logo { image { __typename ... on
  CheckoutAndAccountsConfigurationBrandingImage { image { url } } } maxWidth
  visibility } padding } headingLevel1 { typography { font kerning letterCase
  size weight } } headingLevel2 { typography { font kerning letterCase size
  weight } } headingLevel3 { typography { font kerning letterCase size weight }
  } main { colors { base { accent background border decorative icon text }
  control { accent background border decorative icon selected { accent
  background border decorative icon text } text } primaryButton { accent
  background border decorative hover { accent background border decorative icon
  text } icon text } secondaryButton { accent background border decorative hover
  { accent background border decorative icon text } icon text } } divider {
  borderStyle borderWidth visibility } section { background border borderStyle
  borderWidth colors { base { accent background border decorative icon text }
  control { accent background border decorative icon selected { accent
  background border decorative icon text } text } primaryButton { accent
  background border decorative hover { accent background border decorative icon
  text } icon text } secondaryButton { accent background border decorative hover
  { accent background border decorative icon text } icon text } } cornerRadius
  padding shadow } } merchandiseThumbnail { badge { background } border
  cornerRadius fit } primaryButton { blockPadding border cornerRadius
  inlinePadding typography { font kerning letterCase size weight } }
  secondaryButton { blockPadding border cornerRadius inlinePadding typography {
  font kerning letterCase size weight } } select { border typography { font
  kerning letterCase size weight } } shared { colors { accent button control
  critical decorative info success warning } cornerRadius typography { kerning
  letterCase } } textField { border typography { font kerning letterCase size
  weight } } } designTokens { colors { palette { color1 color2 color3 color4
  color5 color6 color7 color8 color9 color10 color11 color12 color13 color14
  color15 color16 color17 color18 color19 color20 } } cornerRadius { base large
  small } typography { primary { __typename ... on
  CheckoutAndAccountsConfigurationBrandingCustomFontGroup { name loadingStrategy
  base { genericFileId sources weight } bold { genericFileId sources weight } }
  ... on CheckoutAndAccountsConfigurationBrandingShopifyFontGroup { name
  loadingStrategy base { sources weight } bold { sources weight } } } secondary
  { __typename ... on CheckoutAndAccountsConfigurationBrandingCustomFontGroup {
  name loadingStrategy base { genericFileId sources weight } bold {
  genericFileId sources weight } } ... on
  CheckoutAndAccountsConfigurationBrandingShopifyFontGroup { name
  loadingStrategy base { sources weight } bold { sources weight } } } size {
  base ratio } } } surfaces { checkout { components { buyerJourney { visibility
  } cartLink { visibility } content { divider { borderStyle borderWidth
  visibility } } expressCheckout { button { cornerRadius } } footer { alignment
  background colors { base { accent background border decorative icon text }
  control { accent background border decorative icon selected { accent
  background border decorative icon text } text } primaryButton { accent
  background border decorative hover { accent background border decorative icon
  text } icon text } secondaryButton { accent background border decorative hover
  { accent background border decorative icon text } icon text } } content {
  visibility } divided padding position } header { alignment background cartLink
  { contentType image { __typename ... on
  CheckoutAndAccountsConfigurationBrandingImage { image { url } } } } colors {
  base { accent background border decorative icon text } control { accent
  background border decorative icon selected { accent background border
  decorative icon text } text } primaryButton { accent background border
  decorative hover { accent background border decorative icon text } icon text }
  secondaryButton { accent background border decorative hover { accent
  background border decorative icon text } icon text } } divided logo { image {
  __typename ... on CheckoutAndAccountsConfigurationBrandingImage { image { url
  } } } maxWidth visibility } padding position } main { colors { base { accent
  background border decorative icon text } control { accent background border
  decorative icon selected { accent background border decorative icon text }
  text } primaryButton { accent background border decorative hover { accent
  background border decorative icon text } icon text } secondaryButton { accent
  background border decorative hover { accent background border decorative icon
  text } icon text } } divider { borderStyle borderWidth visibility } section {
  background border borderStyle borderWidth colors { base { accent background
  border decorative icon text } control { accent background border decorative
  icon selected { accent background border decorative icon text } text }
  primaryButton { accent background border decorative hover { accent background
  border decorative icon text } icon text } secondaryButton { accent background
  border decorative hover { accent background border decorative icon text } icon
  text } } cornerRadius padding shadow } } orderSummary { backgroundImage {
  __typename ... on CheckoutAndAccountsConfigurationBrandingImage { image { url
  } } } colors { base { accent background border decorative icon text } control
  { accent background border decorative icon selected { accent background border
  decorative icon text } text } primaryButton { accent background border
  decorative hover { accent background border decorative icon text } icon text }
  secondaryButton { accent background border decorative hover { accent
  background border decorative icon text } icon text } } divider { borderStyle
  borderWidth visibility } section { background border borderStyle borderWidth
  colors { base { accent background border decorative icon text } control {
  accent background border decorative icon selected { accent background border
  decorative icon text } text } primaryButton { accent background border
  decorative hover { accent background border decorative icon text } icon text }
  secondaryButton { accent background border decorative hover { accent
  background border decorative icon text } icon text } } cornerRadius padding
  shadow } } } } customerAccounts { components { footer { alignment colors {
  base { accent background border decorative icon text } control { accent
  background border decorative icon selected { accent background border
  decorative icon text } text } primaryButton { accent background border
  decorative hover { accent background border decorative icon text } icon text }
  secondaryButton { accent background border decorative hover { accent
  background border decorative icon text } icon text } } padding } header {
  alignment colors { base { accent background border decorative icon text }
  control { accent background border decorative icon selected { accent
  background border decorative icon text } text } primaryButton { accent
  background border decorative hover { accent background border decorative icon
  text } icon text } secondaryButton { accent background border decorative hover
  { accent background border decorative icon text } icon text } } logo { image {
  __typename ... on CheckoutAndAccountsConfigurationBrandingImage { image { url
  } } } maxWidth } padding } main { colors { base { accent background border
  decorative icon text } control { accent background border decorative icon
  selected { accent background border decorative icon text } text }
  primaryButton { accent background border decorative hover { accent background
  border decorative icon text } icon text } secondaryButton { accent background
  border decorative hover { accent background border decorative icon text } icon
  text } } section { background border borderStyle borderWidth colors { base {
  accent background border decorative icon text } control { accent background
  border decorative icon selected { accent background border decorative icon
  text } text } primaryButton { accent background border decorative hover {
  accent background border decorative icon text } icon text } secondaryButton {
  accent background border decorative hover { accent background border
  decorative icon text } icon text } } cornerRadius padding shadow } } } }
  signIn { components { header { logo { image { __typename ... on
  CheckoutAndAccountsConfigurationBrandingImage { image { url } } } maxWidth }
  padding } main { backgroundImage { __typename ... on
  CheckoutAndAccountsConfigurationBrandingImage { image { url } } } colors {
  base { accent background border decorative icon text } control { accent
  background border decorative icon selected { accent background border
  decorative icon text } text } primaryButton { accent background border
  decorative hover { accent background border decorative icon text } icon text }
  secondaryButton { accent background border decorative hover { accent
  background border decorative icon text } icon text } } section { background
  border borderStyle borderWidth colors { base { accent background border
  decorative icon text } control { accent background border decorative icon
  selected { accent background border decorative icon text } text }
  primaryButton { accent background border decorative hover { accent background
  border decorative icon text } icon text } secondaryButton { accent background
  border decorative hover { accent background border decorative icon text } icon
  text } } cornerRadius padding shadow } } } } } } } }
`;
